In [7]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions
import numpy as np

In [8]:
music = pd.read_csv("/content/tcc_ceds_music.csv")
music1 = pd.read_csv("/content/tcc_ceds_music.csv")

In [25]:
music.head(3)

artist_name                track_name release_date  genre  \
0          [mukesh]  [mohabbat, bhi, jhoothi]       [1950]  [pop]   
1  [frankie, laine]              [i, believe]       [1950]  [pop]   
2    [johnnie, ray]                     [cry]       [1950]  [pop]   

                                              lyrics         topic  
0  [hold, time, feel, break, feel, untrue, convin...     [sadness]  
1  [believe, drop, rain, fall, grow, believe, dar...  [world/life]  
2  [sweetheart, send, letter, goodbye, secret, fe...       [music]

In [13]:
music["release_date"] = music1["release_date"]

<ipython-input-13-5005434eea0c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  music["release_date"] = music1["release_date"]


In [11]:
music = music[["artist_name", "track_name", "genre", "lyrics", "topic"]]

In [16]:
music = music.iloc[:-20000, :]

In [18]:
music.shape

(8372, 6)

In [19]:
music = music[["artist_name", "track_name", "release_date", "genre", "lyrics", "topic"]]

In [21]:
music["lyrics"] = music["lyrics"].apply(lambda x: x.split())

In [22]:
music["genre"] = music["genre"].apply(lambda x: x.split())
music["track_name"] = music["track_name"].apply(lambda x: x.split())
music["topic"] = music["topic"].apply(lambda x: x.split())

In [23]:
music["release_date"] = music["release_date"].apply(lambda x: str(x))
music["release_date"] = music["release_date"].apply(lambda x: x.split())

In [24]:
music["artist_name"] = music["artist_name"].apply(lambda x: str(x))
music["artist_name"] = music["artist_name"].apply(lambda x: x.split())

In [26]:
music["tags"] = music["artist_name"] + music["release_date"] +  music["track_name"] + music["genre"] + music["lyrics"] + music["topic"]

In [27]:
new_df = music[["track_name", "tags"]]

In [28]:
new_df["track_name"] = music1["track_name"]

<ipython-input-28-003f6bbb1b8b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["track_name"] = music1["track_name"]


In [29]:
new_df

track_name  \
0                mohabbat bhi jhoothi   
1                           i believe   
2                                 cry   
3                            patricia   
4                  apopse eida oneiro   
...                               ...   
8367                   louisiana lady   
8368                         cherokee   
8369  beat me daddy, eight to the bar   
8370                lord hold my hand   
8371                         the door   

                                                   tags  
0     [mukesh, 1950, mohabbat, bhi, jhoothi, pop, ho...  
1     [frankie, laine, 1950, i, believe, pop, believ...  
2     [johnnie, ray, 1950, cry, pop, sweetheart, sen...  
3     [pérez, prado, 1950, patricia, pop, kiss, lips...  
4     [giorgos, papadopoulos, 1950, apopse, eida, on...  
...                                                 ...  
8367  [new, riders, of, the, purple, sage, 1971, lou...  
8368  [hank, williams,, jr., 1971, cherokee, country...  
8369  [commander, cody, and, his, lost, planet, airm...  
8370  [dolly, parton, 1971, lord, hold, my, hand, co...  
8371  [george, jones, 1971, the, door, country, hear...  

[8372 rows x 2 columns]

In [30]:
new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))

<ipython-input-30-06f71aee9f58>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x: " ".join(x))


In [31]:
new_df

track_name  \
0                mohabbat bhi jhoothi   
1                           i believe   
2                                 cry   
3                            patricia   
4                  apopse eida oneiro   
...                               ...   
8367                   louisiana lady   
8368                         cherokee   
8369  beat me daddy, eight to the bar   
8370                lord hold my hand   
8371                         the door   

                                                   tags  
0     mukesh 1950 mohabbat bhi jhoothi pop hold time...  
1     frankie laine 1950 i believe pop believe drop ...  
2     johnnie ray 1950 cry pop sweetheart send lette...  
3     pérez prado 1950 patricia pop kiss lips want s...  
4     giorgos papadopoulos 1950 apopse eida oneiro p...  
...                                                 ...  
8367  new riders of the purple sage 1971 louisiana l...  
8368  hank williams, jr. 1971 cherokee country uncle...  
8369  commander cody and his lost planet airmen 1971...  
8370  dolly parton 1971 lord hold my hand country ho...  
8371  george jones 1971 the door country hear sound ...  

[8372 rows x 2 columns]

In [32]:
new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())

<ipython-input-32-fbd31edcc25f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["tags"] = new_df["tags"].apply(lambda x: x.lower())


In [38]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000, stop_words="english")

In [39]:
vectors = cv.fit_transform(new_df["tags"]).toarray()

In [40]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [46]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., '쿵더러러', '티르소스', '해봤다면'], dtype=object)

In [44]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [45]:
def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)


In [47]:
new_df["tags"].apply(stem)

0       mukesh 1950 mohabbat bhi jhoothi pop hold time...
1       franki lain 1950 i believ pop believ drop rain...
2       johnni ray 1950 cri pop sweetheart send letter...
3       pérez prado 1950 patricia pop kiss lip want st...
4       giorgo papadopoulo 1950 apops eida oneiro pop ...
                              ...                        
8367    new rider of the purpl sage 1971 louisiana lad...
8368    hank williams, jr. 1971 cheroke countri uncl k...
8369    command codi and hi lost planet airmen 1971 be...
8370    dolli parton 1971 lord hold my hand countri ho...
8371    georg jone 1971 the door countri hear sound de...
Name: tags, Length: 8372, dtype: object

In [48]:
from sklearn.metrics.pairwise import cosine_similarity


In [51]:
similarity = cosine_similarity(vectors)

In [81]:
similarity[0]

array([1.        , 0.0207656 , 0.23231138, ..., 0.17619604, 0.13619241,
       0.13031774])

In [89]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x: x[1])[1:6]

[(3589, 0.5232045649263551),
 (5864, 0.502689133170655),
 (4439, 0.5018204153893183),
 (2710, 0.4980794852207826),
 (2075, 0.4948075202507773)]

In [71]:
similarity[new_df[new_df["track_name"] == "cherokee"].index[0]]

array([0.034083  , 0.0149513 , 0.02908956, ..., 0.13262819, 0.02614907,
       0.04865219])

In [105]:
new_df["track_name"][0]

'mohabbat bhi jhoothi'

In [108]:
def recommend(music):
  music_index = new_df[new_df["track_name"] == music].index[0]
  distances = similarity[music_index]
  music_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x: x[1])[1:6]

  for i in music_list:
    print(new_df["track_name"][i[0]])


In [111]:
recommend("cry")

cry
feel up
emotions
here in your bedroom
i feel better all over
